### ISSUE TITLE
How to know when crawl finished?

### ISSUE THREAD

**Issue by pittersnider** [brendonboshell/supercrawler#36]
I didn't find on documentation how can we handle when the crawler finished.

**Comment by jayproulx** [comment]
Yeah, I'm running into this myself.  Crawler emits a urllistempty or urllistcomplete event only when catching a RangeError in getNextUrl.  For the moment, for testing, I'm only using the FifoUrlList, and I can see that the list maintained doesn't include any state after the page has been crawled.  I can see that there is an entry in the list for my example page and for robots.txt (404) but neither one is ever removed from the list.

Additionally, there's no way to clean up the list after processing is complete because you can only insert, upsert or get the next item in the list.

Even on my very simple test case, the process is sitting there waiting with a couple of items in the list that won't be removed.

**Comment by jayproulx** [comment]
@brendonboshell I'd be happy to send a PR, if you have a preference for how this will work, I haven't tested with Redis of DB lists yet, and want to get Fifo working first before distributing the processing (no point in running a bunch of Docker containers if they're just going to run perpetually).

**Comment by jayproulx** [comment]
Quick update here, I've just been trying to do this quickly, but I can't seem to delete, splice or update URL's (adding a separate processed property) in the Fifo list, as soon as it's queried again my changes haven't persisted.  The only thing I can think to do at the moment is to keep a separate list of all processed URL's, cross reference every few (5-10) seconds, and kill the process if all of the URLs in the Fifo list are equal to all of the URL's in the processed list.  I'm not sure how else these elements are supposed to be removed, I don't see any splicing or deleting happening in Crawler.js or the list classes.

**Comment by brendonboshell** [comment]
The `urllistcomplete` event should tell you when the crawl is finished if you are not running in a distributed mode. Is there any issues with this not working?

For distributed crawling, the use case is almost always to have the crawling processes running indefinitely, since the crawl queue could be manipulated from other processes (either added by Supercrawler or elsewhere if you are using a custom UrlList). Not only that, but URLs are scheduled for a recrawl after 30 days (at least with RedisUrlList) so the crawl is never finished.

**Comment by brendonboshell** [comment]
^ Please re-open/comment if the above does not answer your question.

**Comment by jayproulx** [comment]
I don't seem to have the option to re-open the ticket, but can definitely confirm that the FifoUrlList is not firing urllistcomplete, I'm using a shadow copy of the queue until I know that all pages have been crawled.

Unless I'm missing something entirely here and I need to be removing things from the queue manually.

I need to be able to stop processing once it's complete, transparently, I've got a Docker swarm handling the crawl until it's complete and autoscaling based on load.  If there's no load, the containers are shut down until load picks up and autoscaling takes over as necessary and those tasks start looking at the queue again.

I can do this right now with my shadow queue and the FifoUrlList, but would prefer to use Redis here if possible (but also had some other issues getting RedisUrlList to work locally, it looked at the first page, but then didn't continue, I haven't gone back to figure out what that was about.

**Comment by jayproulx** [comment]
Also, happy to contribute here wherever I can, let me know how you would like to address these issues and I can send a PR
